input {
  beats {
    port => 5045
    tags => ["filebeat"]
  }
}

filter {
  if "filebeat" in [tags] {

    mutate {
      rename => {
        "[host][name]" => "21hostname"
        "[log][file][path]" => "log_file_path"
      }
      add_field => { "log_source" => "linux" }
    }

    # ─── Parser les logs syslog/auth Ubuntu ───
    if [log_file_path] =~ /auth\.log/ {
      grok {
        match => { "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{HOSTNAME:syslog_host} %{WORD:program}(?:\[%{POSINT:pid}\])?: %{GREEDYDATA:syslog_message}" }
        tag_on_failure => ["_grokparsefailure_auth"]
      }
      grok {
        match => { "syslog_message" => "from %{IP:src_ip}" }
        tag_on_failure => ["_no_ip_found"]
      }
      mutate { add_field => { "event_category" => "authentication" } }

      # Détection SSH
      if [syslog_message] =~ /Failed password/ {
        mutate {
          add_field => {
            "event_description" => "Échec SSH"
            "severity"          => "high"
          }
        }
      } else if [syslog_message] =~ /Accepted password|Accepted publickey/ {
        mutate {
          add_field => {
            "event_description" => "Connexion SSH réussie"
            "severity"          => "low"
          }
        }
      }
    }

    # ─── Syslog général ───
    else if [log_file_path] =~ /syslog/ {
      grok {
        match => { "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{HOSTNAME:syslog_host} %{GREEDYDATA:syslog_message}" }
        tag_on_failure => ["_grokparsefailure_syslog"]
      }
      mutate { add_field => { "event_category" => "system" } }
    }
  }
}

output {
  if "filebeat" in [tags] {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      user => "elastic"
      password => "changeme"
      index => "linux-logs-%{+YYYY.MM.dd}"
      action   => "create"
    }
  }
}
